import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import Ajv from 'ajv';
import { serializePackFile } from '../file';
import { STANDARD_52 } from '../standard52';
import { serializeScenarioFile, type Scenario } from '$lib/scenario/file';

// The schemas served from static/ (generated by `bun run schemas`) must
// accept what the exporters write.
const staticDir = join(__dirname, '../../../../static');
// strict:false — the schemas carry `x-tableplace-*` provenance annotations,
// which ajv's strict mode would reject as unknown keywords
const ajv = new Ajv({ allowUnionTypes: true, strict: false });
const validatePack = ajv.compile(
	JSON.parse(readFileSync(join(staticDir, 'pack.schema.json'), 'utf-8'))
);
const validateScenario = ajv.compile(
	JSON.parse(readFileSync(join(staticDir, 'scenario.schema.json'), 'utf-8'))
);

describe('generated JSON schemas', () => {
	it('pack.schema.json validates the STANDARD_52 pack file', () => {
		const ok = validatePack(JSON.parse(serializePackFile(STANDARD_52)));
		expect(validatePack.errors ?? []).toEqual([]);
		expect(ok).toBe(true);
	});

	it('pack.schema.json rejects a file missing the discriminator', () => {
		const file = JSON.parse(serializePackFile(STANDARD_52));
		delete file.tbpp;
		expect(validatePack(file)).toBe(false);
	});

	it('scenario.schema.json validates a saved scenario file', () => {
		const scenario: Scenario = {
			name: 'duel',
			createdAt: 1700000000000,
			state: {
				cards: { 'card:seat0:main-AS': { position: [0, 0.1, 0], faceImageUrl: 'gen:std52/AS' } },
				decks: {
					'deck:seat0:main': {
						id: 'deck:seat0:main',
						position: [8.5, 0.4, 4.5],
						rotation: [0, 0, 0],
						cards: [{ id: 'card:seat0:main-2S', faceImageUrl: 'gen:std52/2S' }]
					}
				},
				pieces: { 'piece:seat0:hp-0': { kind: 'counter', name: 'HP', value: 20, maxValue: 20 } },
				overlays: { 'overlay:map': { imageUrl: 'https://x/map.webp', ratio: 1.6, scale: 10 } },
				players: { seat0: { id: 'seat0', seat: 0, joinTimestamp: 0, tray: {}, metadata: {} } }
			}
		};
		const ok = validateScenario(JSON.parse(serializeScenarioFile(scenario)));
		expect(validateScenario.errors ?? []).toEqual([]);
		expect(ok).toBe(true);
	});

	it('scenario.schema.json validates a v2 pack-referencing scenario file', () => {
		const scenario: Scenario = {
			name: 'stacked-duel',
			createdAt: 1700000000000,
			state: {
				pieces: { 'piece:seat0:objective-0': { kind: 'token', name: 'Objective' } }
			},
			packs: [
				{ id: 'standard-52', source: 'builtin' },
				{ id: 'my-proto', source: 'https://example.com/my-proto.tbpp.json' }
			],
			placements: [
				{
					kind: 'deck',
					pack: 'standard-52',
					content: 'main',
					seat: 0,
					position: [8.5, 0.4, 4.5],
					rotation: [0, 0, 0],
					isFaceUp: false,
					order: ['7H', 'AS', '2C'],
					shuffleOnLoad: false
				},
				{ kind: 'deck', pack: 'my-proto', content: 'draw', seat: 1, shuffleOnLoad: true },
				{ kind: 'piece', pack: 'my-proto', content: '0', seat: 1, value: 12 },
				{ kind: 'overlay', pack: 'my-proto', content: '0', scale: 14 }
			]
		};
		const file = JSON.parse(serializeScenarioFile(scenario));
		expect(file.tbps).toBe(2);
		const ok = validateScenario(file);
		expect(validateScenario.errors ?? []).toEqual([]);
		expect(ok).toBe(true);
	});

	it('scenario.schema.json rejects a wrong-version discriminator', () => {
		expect(validateScenario({ tbps: 3, name: 'x', createdAt: 1, state: {} })).toBe(false);
	});

	it('scenario.schema.json rejects an unknown placement kind', () => {
		expect(
			validateScenario({
				tbps: 2,
				name: 'x',
				createdAt: 1,
				state: {},
				packs: [{ id: 'standard-52' }],
				placements: [{ kind: 'zone', pack: 'standard-52', content: 'main' }]
			})
		).toBe(false);
	});
});
